[package]
name = "bracket"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
logos = "0.11.4"
thiserror = "^1.0"
log = "^0.4"
serde = "^1.0"
serde_json = "^1.0"
unicode-width = "^0.1"

[dev-dependencies]
pretty_env_logger = "0.4"
