[package]
name = "hbs"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
thiserror = "1"
logos = { version = "0.11.4", default-features = false }
logos-derive = "0.11.5"
regex = "1.4.1"
serde = "1.0.117"
serde_json = "1.0.59"
